import "@styles/globals.css";
import { Providers } from "./Providers";
import Nav from "@components/Nav";
import { Inter } from "next/font/google";

// If loading a variable font, you don't need to specify the font weight
const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});
export const metadata = {
  title: "Chat App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={inter.className}>
      <body>
        <Nav />
        {children}
      </body>
    </html>
  );
}
